/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package centrivaccinali;

/**
 *
 * @author andre
 */
public class RegistrazioneCentroVaccinale extends javax.swing.JFrame {

    /**
     * Creates new form registraCentroVaccinale
     */
    public RegistrazioneCentroVaccinale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_RegistrazioneCentroVaccinale = new javax.swing.JPanel();
        title_RegistrazioneCentroVaccinale = new javax.swing.JLabel();
        datiPnl_RegistrazioneCentroVaccinale = new javax.swing.JPanel();
        name_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        qualificatore_RegistrazioneCentroVaccinale = new javax.swing.JComboBox<>();
        via_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        n_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        tipologia_RegistrazioneCentroVaccinale = new javax.swing.JComboBox<>();
        comune_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        prov_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        cap_RegistrazioneCentroVaccinale = new javax.swing.JTextField();
        ann_RegistrazioneCentroVaccinale = new javax.swing.JButton();
        add_RegistrazioneCentroVaccinale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        Panel_RegistrazioneCentroVaccinale.setBackground(new java.awt.Color(255, 255, 255));

        title_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title_RegistrazioneCentroVaccinale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistrazioneCentroVaccinale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/centrivaccinali-logo.png"))); // NOI18N
        title_RegistrazioneCentroVaccinale.setText("Registra Centro Vaccinale");

        datiPnl_RegistrazioneCentroVaccinale.setBackground(new java.awt.Color(255, 255, 255));
        datiPnl_RegistrazioneCentroVaccinale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Inserisci i dati ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        datiPnl_RegistrazioneCentroVaccinale.setToolTipText("");

        name_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        name_RegistrazioneCentroVaccinale.setText("Nome Centro Vaccinale");
        name_RegistrazioneCentroVaccinale.setToolTipText("");
        name_RegistrazioneCentroVaccinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_RegistrazioneCentroVaccinaleActionPerformed(evt);
            }
        });

        qualificatore_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        qualificatore_RegistrazioneCentroVaccinale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Via", "Viale", "Piazza" }));

        via_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        via_RegistrazioneCentroVaccinale.setText("Nome della via");

        n_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        n_RegistrazioneCentroVaccinale.setText("N°");
        n_RegistrazioneCentroVaccinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_RegistrazioneCentroVaccinaleActionPerformed(evt);
            }
        });

        tipologia_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tipologia_RegistrazioneCentroVaccinale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ospedaliero", "Aziendale", "Hub" }));

        comune_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comune_RegistrazioneCentroVaccinale.setText("Comune");

        prov_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        prov_RegistrazioneCentroVaccinale.setText("Prov.");
        prov_RegistrazioneCentroVaccinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prov_RegistrazioneCentroVaccinaleActionPerformed(evt);
            }
        });

        cap_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cap_RegistrazioneCentroVaccinale.setText("CAP");

        javax.swing.GroupLayout datiPnl_RegistrazioneCentroVaccinaleLayout = new javax.swing.GroupLayout(datiPnl_RegistrazioneCentroVaccinale);
        datiPnl_RegistrazioneCentroVaccinale.setLayout(datiPnl_RegistrazioneCentroVaccinaleLayout);
        datiPnl_RegistrazioneCentroVaccinaleLayout.setHorizontalGroup(
            datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                        .addComponent(comune_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(prov_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cap_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datiPnl_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                        .addComponent(qualificatore_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(via_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(n_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, datiPnl_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                        .addComponent(name_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipologia_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        datiPnl_RegistrazioneCentroVaccinaleLayout.setVerticalGroup(
            datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_RegistrazioneCentroVaccinale)
                    .addComponent(tipologia_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(n_RegistrazioneCentroVaccinale)
                    .addComponent(qualificatore_RegistrazioneCentroVaccinale)
                    .addComponent(via_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(datiPnl_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cap_RegistrazioneCentroVaccinale)
                    .addComponent(prov_RegistrazioneCentroVaccinale)
                    .addComponent(comune_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        ann_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ann_RegistrazioneCentroVaccinale.setText("Annulla");
        ann_RegistrazioneCentroVaccinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ann_RegistrazioneCentroVaccinaleActionPerformed(evt);
            }
        });

        add_RegistrazioneCentroVaccinale.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        add_RegistrazioneCentroVaccinale.setText("Aggiungi");
        add_RegistrazioneCentroVaccinale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_RegistrazioneCentroVaccinaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_RegistrazioneCentroVaccinaleLayout = new javax.swing.GroupLayout(Panel_RegistrazioneCentroVaccinale);
        Panel_RegistrazioneCentroVaccinale.setLayout(Panel_RegistrazioneCentroVaccinaleLayout);
        Panel_RegistrazioneCentroVaccinaleLayout.setHorizontalGroup(
            Panel_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datiPnl_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                        .addComponent(ann_RegistrazioneCentroVaccinale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add_RegistrazioneCentroVaccinale)))
                .addContainerGap())
        );
        Panel_RegistrazioneCentroVaccinaleLayout.setVerticalGroup(
            Panel_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_RegistrazioneCentroVaccinaleLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(title_RegistrazioneCentroVaccinale)
                .addGap(10, 10, 10)
                .addComponent(datiPnl_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_RegistrazioneCentroVaccinaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ann_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_RegistrazioneCentroVaccinale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_RegistrazioneCentroVaccinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_RegistrazioneCentroVaccinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_RegistrazioneCentroVaccinaleActionPerformed

    private void n_RegistrazioneCentroVaccinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_RegistrazioneCentroVaccinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_RegistrazioneCentroVaccinaleActionPerformed

    private void prov_RegistrazioneCentroVaccinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prov_RegistrazioneCentroVaccinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prov_RegistrazioneCentroVaccinaleActionPerformed

    private void add_RegistrazioneCentroVaccinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_RegistrazioneCentroVaccinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_RegistrazioneCentroVaccinaleActionPerformed

    private void ann_RegistrazioneCentroVaccinaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ann_RegistrazioneCentroVaccinaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ann_RegistrazioneCentroVaccinaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrazioneCentroVaccinale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrazioneCentroVaccinale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrazioneCentroVaccinale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrazioneCentroVaccinale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrazioneCentroVaccinale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_RegistrazioneCentroVaccinale;
    private javax.swing.JButton add_RegistrazioneCentroVaccinale;
    private javax.swing.JButton ann_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField cap_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField comune_RegistrazioneCentroVaccinale;
    private javax.swing.JPanel datiPnl_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField n_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField name_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField prov_RegistrazioneCentroVaccinale;
    private javax.swing.JComboBox<String> qualificatore_RegistrazioneCentroVaccinale;
    private javax.swing.JComboBox<String> tipologia_RegistrazioneCentroVaccinale;
    private javax.swing.JLabel title_RegistrazioneCentroVaccinale;
    private javax.swing.JTextField via_RegistrazioneCentroVaccinale;
    // End of variables declaration//GEN-END:variables
}
